### ISSUE TITLE
Region 1/2/3 frequency

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-region-tool#11]
Should maybe be Main, Secondary, Tertiary or something?

**Comment by shawaj** [comment]
> Should maybe be Main, Secondary, Tertiary or something?

Changed on the results but still need to change on map.

@Louisreed where does the map overlay text get set? From the spreadsheet?

**Comment by Louisreed** [comment]
@shawaj It's the column head set in the spreadsheet, I've updated the js file see here https://github.com/NebraLtd/helium-region-tool/pull/13/commits/f1791afec6f411eabb4f94c11f7e6e4291f8b43a
