### ISSUE TITLE
Auto update when hplans CSV updates

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-region-tool#3]
Auto pull in changes

**Comment by Louisreed** [comment]
I've already configured a CRON type instance on the spreadsheet that updates from the hplans source data every 24hrs, so the tool is kept up to date!

**Comment by Louisreed** [comment]
@shawaj I've already configured a CRON type instance on the spreadsheet that updates from the hplans source data every 24hrs via the [Apps Scripts extension](https://script.google.com/u/2/home/projects/1sVJSv3vKj7J5LZLGKSysyWg2E7Nk7ASoq4YgTnFh9Wp7M7nv0qjO58Od/edit)

**Comment by shawaj** [comment]
Amazing 👍👍👍
